// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxAQxp_pdJBHoHhZqpJZdtOMJOQGVXps8',
    appId: '1:978999179050:web:e1dec8b57664b45cb8d053',
    messagingSenderId: '978999179050',
    projectId: 'test-c2d1d',
    authDomain: 'test-c2d1d.firebaseapp.com',
    storageBucket: 'test-c2d1d.firebasestorage.app',
    measurementId: 'G-8W6EM8ZVSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdKkaVzMCA5AFsHLsKRKll0boHZ-T9R5U',
    appId: '1:978999179050:android:293529e59848ca0eb8d053',
    messagingSenderId: '978999179050',
    projectId: 'test-c2d1d',
    storageBucket: 'test-c2d1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYkAf6gIacAwj2R77-2X10wteS-NvBDQE',
    appId: '1:978999179050:ios:2b4620ff7ab87256b8d053',
    messagingSenderId: '978999179050',
    projectId: 'test-c2d1d',
    storageBucket: 'test-c2d1d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYkAf6gIacAwj2R77-2X10wteS-NvBDQE',
    appId: '1:978999179050:ios:2b4620ff7ab87256b8d053',
    messagingSenderId: '978999179050',
    projectId: 'test-c2d1d',
    storageBucket: 'test-c2d1d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxAQxp_pdJBHoHhZqpJZdtOMJOQGVXps8',
    appId: '1:978999179050:web:8081926c33c6938bb8d053',
    messagingSenderId: '978999179050',
    projectId: 'test-c2d1d',
    authDomain: 'test-c2d1d.firebaseapp.com',
    storageBucket: 'test-c2d1d.firebasestorage.app',
    measurementId: 'G-VCGK2NGXJW',
  );
}
